package chapter12.ex28;

/**
 * Created by pyvov on 14.01.2017.
 */
public class Main {
    public static void main(String[] args) {
//        try {
            throw new MyException("Exception in main()");
//        } catch (MyException e) {
//            System.out.println(e.getMessage());
//        }
    }
}
